// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0UOtsWAGBxozij1OrWQhuEK-RIGiqYZI',
    appId: '1:521442826904:web:c0476ba4c7456617cd4eed',
    messagingSenderId: '521442826904',
    projectId: 'loan-app-d6852',
    authDomain: 'loan-app-d6852.firebaseapp.com',
    storageBucket: 'loan-app-d6852.appspot.com',
    measurementId: 'G-Q23CYJCFZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjkH5PPOlM2aFf0DNJdCFY4sRLNd9ZqME',
    appId: '1:521442826904:android:19dd384e829073c9cd4eed',
    messagingSenderId: '521442826904',
    projectId: 'loan-app-d6852',
    storageBucket: 'loan-app-d6852.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiL95iJp9W2iG79s1NF5LA3aLxtHgjACs',
    appId: '1:521442826904:ios:4cb770fd20cece53cd4eed',
    messagingSenderId: '521442826904',
    projectId: 'loan-app-d6852',
    storageBucket: 'loan-app-d6852.appspot.com',
    iosClientId: '521442826904-diq7a6tv8e9ccro3o0474uc087s1qv74.apps.googleusercontent.com',
    iosBundleId: 'com.example.loanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiL95iJp9W2iG79s1NF5LA3aLxtHgjACs',
    appId: '1:521442826904:ios:4cb770fd20cece53cd4eed',
    messagingSenderId: '521442826904',
    projectId: 'loan-app-d6852',
    storageBucket: 'loan-app-d6852.appspot.com',
    iosClientId: '521442826904-diq7a6tv8e9ccro3o0474uc087s1qv74.apps.googleusercontent.com',
    iosBundleId: 'com.example.loanApp',
  );
}
